### ISSUE TITLE
Open Game Panel Support

### ISSUE THREAD

**Issue by crashzk** [ghostcap-gaming/SAUB-CS2-Server-Automatic-Update-Bot#1]
Would it be possible to support [Open Game Panel](https://github.com/OpenGamePanel)?

**Comment by pedrotski** [comment]
If they have an API you would be able to fork it and add it, But I'm personally not really looking to support any other platforms right now, sorry.

I chose WISP and Pterodactyl as they're the most widely used management panels atm.
